### PR TITLE
Update dependencies to latest & allow for overrides

### PR DESCRIPTION
**Pull request by lostthetrail**
Previous version of lab was producing the following message during tests:
```
The following leaks were detected:Reflect
```

Added overrides to allow for control over defaults.

Let me know if there is anything I missed.

### CODE REVIEW

**Comment by lostthetrail** [comment]
@idoshamun Head's up, incase a watch isn't setup.

**Comment by idoshamun** [comment]
Watch is on, of course, had a busy day :)

Thanks for the contribution :+1:

**Comment by lostthetrail** [comment]
Thanks!

**Comment by lostthetrail** [comment]
@idoshamun What is your normal cadence for releasing the project?

**Comment by idoshamun** [comment]
Usually I release a new version after each PR.

I just published yours in version 1.4.0

**Pull request merged**
